language: ruby
cache: bundler

rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - truffleruby-head

gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_master.gemfile

matrix:
  fast_finish: true
  # Run Danger only once
  include:
    - rvm: 2.5
      gemfile: gemfiles/rails_5_2.gemfile
      script: bundle exec danger
  allow_failures:
    - gemfile: gemfiles/rails_master.gemfile
    - rvm: ruby-head
