development:
  sessions:
    default:
      database: doorkeeper-mongoid-development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        safe: true
test:
  sessions:
    default:
      database: doorkeeper-mongoid-test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        safe: true
